//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNotepad
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailAdress
    {
        public int Id { get; set; }
        public string Sender { get; set; }
        public string Addressee { get; set; }
        public string Message { get; set; }
    }
}
